"""Add profile fields to user and fix password_hash length

Revision ID: 5d4aaebcf742
Revises: cac620c500b4
Create Date: 2025-05-12 00:14:16.698681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4aaebcf742'
down_revision = 'cac620c500b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=256), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('theme')
        batch_op.drop_column('bio')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
