"""Add time_limit to Quiz

Revision ID: 61dd01031461
Revises: 5d4aaebcf742
Create Date: 2025-05-12 06:02:33.739149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dd01031461'
down_revision = '5d4aaebcf742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('time_limit')

    # ### end Alembic commands ###
