export const roomThemes = {
  forest: {
    id: 'forest',
    label: 'Forest Treehouse',
    description: 'Lantern-lit canopy, mossy greens, gentle rain + fireflies.',
    palette: {
      primary: '#5f8d4e',
      secondary: '#c18654',
      background: '#f5f1ea',
      surface: '#ffffff',
      textPrimary: '#1f271b',
      textSecondary: '#4d5c45',
    },
    gradient: 'linear-gradient(180deg,#f9f6ef,#ecf1e2)',
    trailTexture: 'none',
    accentIcon: '🌿',
    ambientSound: 'Soft rain + fireflies',
    spotifyDefault: 'https://open.spotify.com/playlist/37i9dQZF1DX8Uebhn9wzrS',
    decorations: [],
  },
  cabin: {
    id: 'cabin',
    label: 'Cozy Cabin',
    description: 'Amber fireplace glow, wooden desks, snowy windows.',
    palette: {
      primary: '#c07a45',
      secondary: '#a74c36',
      background: '#fbf1e7',
      surface: '#fffaf5',
      textPrimary: '#3a2617',
      textSecondary: '#71503f',
    },
    gradient: 'linear-gradient(180deg,#fdebe0,#f7dcc3)',
    trailTexture: 'none',
    accentIcon: '🪵',
    ambientSound: 'Crackling fireplace',
    spotifyDefault: 'https://open.spotify.com/playlist/37i9dQZF1DWVzZlRWgqAGH',
    decorations: [],
  },
  space: {
    id: 'space',
    label: 'Space Station',
    description: 'Neon blues, holographic panels, cosmic hum.',
    palette: {
      primary: '#5db0ff',
      secondary: '#83aaff',
      background: '#050b18',
      surface: '#101b2f',
      textPrimary: '#f8fbff',
      textSecondary: '#c5d5ff',
    },
    gradient: 'linear-gradient(180deg,#070d1b,#0f1b35)',
    trailTexture: 'none',
    accentIcon: '🛰️',
    ambientSound: 'Console hum + starship drone',
    spotifyDefault: 'https://open.spotify.com/playlist/37i9dQZF1DX5trt9i14X7j',
    decorations: [],
  },
  underwater: {
    id: 'underwater',
    label: 'Underwater Library',
    description: 'Floating jellyfish lamps, bubbles, coral shimmer.',
    palette: {
      primary: '#4ab0c9',
      secondary: '#3c7aa6',
      background: '#e0f4fb',
      surface: '#ffffff',
      textPrimary: '#0f3447',
      textSecondary: '#3a6a7c',
    },
    gradient: 'linear-gradient(180deg,#e8f7ff,#c7e6ef)',
    trailTexture: 'none',
    accentIcon: '🐚',
    ambientSound: 'Water hush + bubbles',
    spotifyDefault: 'https://open.spotify.com/playlist/37i9dQZF1DX2TRYkJECvfC',
    decorations: [],
  },
  cyber: {
    id: 'cyber',
    label: 'Neon Cyber Loft',
    description: 'Synthwave glow, holographic panels, glitch sparkles.',
    palette: {
      primary: '#d777ff',
      secondary: '#7c8bff',
      background: '#070413',
      surface: '#1b1030',
      textPrimary: '#fef5ff',
      textSecondary: '#d4c8ff',
    },
    gradient: 'linear-gradient(180deg,#130523,#200f33)',
    trailTexture: 'none',
    accentIcon: '⚡',
    ambientSound: 'Synth pads + distant city',
    spotifyDefault: 'https://open.spotify.com/playlist/37i9dQZF1DX4sWSpwq3LiO',
    decorations: [],
  },
};

export const defaultRoomKey = 'forest';
